version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  affiliate-network:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
