federation_version: 2 # Without this line, Rover uses Federation 1
subgraphs:

  affiliate-network:
    routing_url: http://AFFILIATE_NETWORK_URL/graphql
    schema:
      file: ./contracts/graphql/affiliate-network.graphql

  campaign:
    routing_url: http://CAMPAIGN_URL/graphql
    schema:
      file: ./contracts/graphql/campaign.graphql

  offer:
    routing_url: http://OFFER_URL/graphql
    schema:
      file: ./contracts/graphql/offer.graphql

  traffic-source:
    routing_url: http://TRAFFIC_SOURCE_URL/graphql
    schema:
      file: ./contracts/graphql/traffic-source.graphql
