apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign
  labels:
    app: campaign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaign
  template:
    metadata:
      labels:
        app: campaign
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: campaign
          image: tds/base
          imagePullPolicy: IfNotPresent
          command: ['node', './dist/services/campaign/src/main.js']
          envFrom:
            - configMapRef:
                name: app-config
