apiVersion: apps/v1
kind: Deployment
metadata:
  name: click
  labels:
    app: click
spec:
  replicas: 1
  selector:
    matchLabels:
      app: click
  template:
    metadata:
      labels:
        app: click
    spec:
      containers:
        - name: click
          image: tds/base
          imagePullPolicy: IfNotPresent
          command: ['node', './dist/services/click/src/main.js']
          envFrom:
            - configMapRef:
                name: app-config
