apiVersion: v1
kind: Service
metadata:
  name: offer
spec:
  selector:
    app: offer
  type: LoadBalancer
  ports:
    - name: graphql
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 3001
      targetPort: 3001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer
  labels:
    app: offer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer
  template:
    metadata:
      labels:
        app: offer
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: offer
          image: tds/base
          imagePullPolicy: IfNotPresent
          command: ['node', './dist/services/offer/src/main.js']
          envFrom:
            - configMapRef:
                name: app-config
