apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer
  labels:
    app: offer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer
  template:
    metadata:
      labels:
        app: offer
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: offer
          image: tds/base
          imagePullPolicy: IfNotPresent
          command: ['node', './dist/services/offer/src/main.js']
          envFrom:
            - configMapRef:
                name: app-config
