apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: affiliate-network
spec:
  selector:
    app: affiliate-network
  ports:
    - name: graphql
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 3001
      targetPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: campaign
spec:
  selector:
    app: campaign
  ports:
    - name: graphql
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 3001
      targetPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: click
spec:
  selector:
    app: click
  ports:
    - name: graphql
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 3001
      targetPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: offer
spec:
  selector:
    app: offer
  ports:
    - name: graphql
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 3001
      targetPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: traffic-source
spec:
  selector:
    app: traffic-source
  ports:
    - name: graphql
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 3001
      targetPort: 3001
