apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: affiliate-network
spec:
  selector:
    app: affiliate-network
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
