apiVersion: v1
kind: Service
metadata:
  name: traffic-source
spec:
  selector:
    app: traffic-source
  type: LoadBalancer
  ports:
    - name: graphql
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 3001
      targetPort: 3001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-source
  labels:
    app: traffic-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-source
  template:
    metadata:
      labels:
        app: traffic-source
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: traffic-source
          image: tds/base
          imagePullPolicy: IfNotPresent
          command: ['node', './dist/services/traffic-source/src/main.js']
          envFrom:
            - configMapRef:
                name: app-config
